# ref: https://computingforgeeks.com/how-to-install-and-configure-gitlab-on-centos-rhel/
web:
  image: 'gitlab/gitlab-ce:latest'
  container_name: 'gitlab-local'
  restart: always
  hostname: 'gitlab.local.com'
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'https://gitlab.local.com'
      gitlab_rails['smtp_enable'] = true
      gitlab_rails['smtp_address'] = "smtp.gmail.com"
      gitlab_rails['smtp_port'] = 587
      gitlab_rails['smtp_user_name'] = ${USER_EMAIL}
      gitlab_rails['smtp_password'] = ${USER_PASSWORD}
      gitlab_rails['smtp_domain'] = "smtp.gmail.com"
      gitlab_rails['smtp_authentication'] = "login"
      gitlab_rails['smtp_enable_starttls_auto'] = true
      gitlab_rails['smtp_tls'] = false
      gitlab_rails['smtp_openssl_verify_mode'] = 'peer'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - '9080:80'
    - '9443:443'
    - '9022:22'
    - '9587:587'
  volumes:
    - './srv/gitlab/config:/etc/gitlab'
    - './srv/gitlab/logs:/var/log/gitlab'
    - './srv/gitlab/data:/var/opt/gitlab'

